apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: scholzma
spec:
  replicas: 2
  selector:
    matchLabels:
        app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-rest-service
        image: docker.at41tools.k8s.aws.msgoat.eu/cxp/helloworldrest-scholzma:0.0.1

