apiVersion: v1
kind: Service
metadata:
  namespace: scholzma
  creationTimestamp: null
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloworld
  type: ClusterIP
status:
  loadBalancer: {}
